// AUTH
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAIL = 'GET_LOGIN_FAIL';

export const GET_REGISTER_SUCCESS = 'GET_REGISTER_SUCCESS';
export const GET_REGISTER_FAIL = 'GET_REGISTER_FAIL';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const GET_AKUN_SUCCESS = 'GET_AKUN_SUCCESS';
export const GET_AKUN_FAIL = 'GET_AKUN_FAIL';
export const GET_AKUN_LOADING = 'GET_AKUN_LOADING';

export const PUT_PASSWORD_SUCCESS = 'PUT_PASSWORD_SUCCESS';
export const PUT_PASSWORD_FAIL = 'PUT_PASSWORD_FAIL';

export const LOGOUT = 'LOGOUT';
