// BUYER PRODUCT
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';

// BUYER DETAIL
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS';
export const GET_DETAIL_PRODUCT_FAIL = 'GET_DETAIL_PRODUCT_FAIL';
export const GET_DETAIL_PRODUCT_LOADING = 'GET_DETAIL_PRODUCT_LOADING';

// POST BID
export const BID_PRODUCT_SUCCESS = '@BID_PRODUCT_SUCCESS';
export const BID_PRODUCT_FAILED = '@BID_PRODUCT_FAILED';

// GET BID
export const GET_ALL_BID_SUCCESS = '@GET_ALL_BID_SUCCESS';
export const GET_ALL_BID_FAILED = '@GET_ALL_BID_FAILED';

export const PUT_BID_SUCCESS = '@PUT_BID_SUCCESS';
export const PUT_BID_FAILED = '@PUT_BID_FAILED';
