// BUYER PRODUCT
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';

// BUYER DETAIL
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS';
export const GET_DETAIL_PRODUCT_FAIL = 'GET_DETAIL_PRODUCT_FAIL';
export const GET_DETAIL_PRODUCT_LOADING = 'GET_DETAIL_PRODUCT_LOADING';

// POST BID
export const BID_PRODUCT_SUCCESS = '@BID_PRODUCT_SUCCESS';
export const BID_PRODUCT_FAILED = '@BID_PRODUCT_FAILED';

// GET BID
export const GET_ALL_BID_SUCCESS = '@GET_ALL_BID_SUCCESS';
export const GET_ALL_BID_FAILED = '@GET_ALL_BID_FAILED';

export const PUT_BID_SUCCESS = '@PUT_BID_SUCCESS';
export const PUT_BID_FAILED = '@PUT_BID_FAILED';

// DELETE BID
export const DELETE_BID_SUCCESS = '@DELETE_BID_SUCCESS';
export const DELETE_BID_FAILED = '@DELETE_BID_FAILED';

// GET WISHLIST
export const GET_WISHLIST_SUCCESS = '@GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAILED = '@DGET_WISHLIST__FAILED';
export const GET_WISHLIST_LOADING = '@GET_WISHLIST_LOADING';

// POST WISLIST
export const ADD_WISHLIST_SUCCESS = '@ADD_WISHLIST_SUCCESS';
export const ADD_WISHLIST_FAILED = '@ADD_WISHLIST_FAILED';

// DELETE WISHLIST
export const DELETE_WISHLIST_SUCCESS = '@DELETE_WISHLIST_SUCCESS';
export const DELETE_WISHLIST_FAILED = '@DELETE_WISHLIST_FAILED';

// GET WISHLIST BY ID
export const GET_WISHLIST_BY_ID_SUCCESS = '@GET_WISHLIST_BY_ID_SUCCESS';
export const GET_WISHLIST_BY_ID_FAILED = '@GET_WISHLIST_BY_ID_FAILED';
