// GET PRODUCT SELLER
export const GET_PRODUCT_SELLER_SUCCESS = 'GET_PRODUCT_SELLER_SUCCESS';
export const GET_PRODUCT_SELLER_FAIL = 'GET_PRODUCT_SELLER_FAIL';
export const GET_PRODUCT_SELLER_LOADING = 'GET_PRODUCT_SELLER_LOADING';
