export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAIL = 'GET_HISTORY_FAIL';
export const GET_HISTORY_LOADING = 'GET_HISTORY_LOADING';

export const GET_HOSTORY_ID_SUCCESS = 'GET_HISTORY_ID_SUCCESS';
export const GET_HISTORY_ID_FAIL = 'GET_HISTORY_ID_FAIL';
export const GET_HISTORY_ID_LOADING = 'GET_HISTORY_ID_LOADING';
