// GLOBAL
export const SET_LOADING = 'SET_LOADING';

// AUTH
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAIL = 'GET_LOGIN_FAIL';
export const GET_LOGIN_LOADING = 'GET_LOGIN_LOADING';

export const GET_REGISTER_SUCCESS = 'GET_REGISTER_SUCCESS';
export const GET_REGISTER_FAIL = 'GET_REGISTER_FAIL';
export const GET_REGISTER_LOADING = 'GET_REGISTER_LOADING';
