// GLOBAL
export const SET_LOADING = 'SET_LOADING';

// AUTH
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAIL = 'GET_LOGIN_FAIL';

export const GET_REGISTER_SUCCESS = 'GET_REGISTER_SUCCESS';
export const GET_REGISTER_FAIL = 'GET_REGISTER_FAIL';

// HOME
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';

export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';

// AKUN
export const GET_AKUN_SUCCESS = 'GET_AKUN_SUCCESS';
export const GET_AKUN_FAIL = 'GET_AKUN_FAIL';
export const GET_AKUN_LOADING = 'GET_AKUN_LOADING';

// PROFILE
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

// LOGOUT
export const LOGOUT = 'LOGOUT';
