export const GET_NOTIFIKASI_SUCCESS = 'GET_NOTIFIKASI_SUCCESS';
export const GET_NOTIFIKASI_FAIL = 'GET_NOTIFIKASI_FAIL';
export const GET_NOTIFIKASI_LOADING = 'GET_NOTIFIKASI_LOADING';

export const GET_NOTIFIKASI_ID_SUCCESS = 'GET_NOTIFIKASI_ID_SUCCESS';
export const GET_NOTIFIKASI_ID_FAIL = 'GET_NOTIFIKASI_ID_FAIL';
export const GET_NOTIFIKASI_ID_LOADING = 'GET_NOTIFIKASI_ID_LOADING';

export const PATCH_NOTIFIKASI_SUCCESS = 'PATCH_NOTIFIKASI_SUCCESS';
export const PATCH_NOTIFIKASI_FAIL = 'PATCH_NOTIFIKASI_FAIL';
export const PATCH_NOTIFIKASI_LOADING = 'PATCH_NOTIFIKASI_LOADING';
