// SELLER PRODUCT
export const GET_SELLER_PRODUCT_SUCCESS = 'GET_SELLER_PRODUCT_SUCCESS';
export const GET_SELLER_PRODUCT_FAIL = 'GET_SELLER_PRODUCT_FAIL';
export const GET_SELLER_PRODUCT_LOADING = 'GET_SELLER_PRODUCT_LOADING';

export const GET_PRODUCT_SELLER_ID_SUCCESS = 'GET_PRODUCT_SELLER_ID_SUCCESS';
export const GET_PRODUCT_SELLER_ID_FAIL = 'GET_PRODUCT_SELLER_ID_FAIL';
export const GET_PRODUCT_SELLER_ID_LOADING = 'GET_PRODUCT_SELLER_ID_LOADING';

export const GET_PRODUCT_DIMINATI = 'GET_PRODUCT_DIMINATI';

export const GET_PRODUCT_TERJUAL = 'GET_PRODUCT_TERJUAL';

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';
export const ADD_PRODUCT_LOADING = 'ADD_PRODUCT_LOADING';

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';
export const UPDATE_PRODUCT_LOADING = 'UPDATE_PRODUCT_LOADING';

export const PATCH_PRODUCT_SUCCESS = 'PATCH_PRODUCT_SUCCESS';
export const PATCH_PRODUCT_FAIL = 'PATCH_PRODUCT_FAIL';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_LOADING = 'DELETE_PRODUCT_LOADING';

// SELLER CATEGORY
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';

// SELLER ORDER
export const GET_ORDER_SELLER_SUCCESS = 'GET_ORDER_SELLER_SUCCESS';
export const GET_ORDER_SELLER_FAIL = 'GET_ORDER_SELLER_FAIL';
export const GET_ORDER_SELLER_LOADING = 'GET_ORDER_SELLER_LOADING';

export const GET_ORDER_SELLER_ID_SUCCESS = 'GET_ORDER_SELLER_ID_SUCCESS';
export const GET_ORDER_SELLER_ID_FAIL = 'GET_ORDER_SELLER_ID_FAIL';
export const GET_ORDER_SELLER_ID_LOADING = 'GET_ORDER_SELLER_ID_LOADING';

export const PATCH_ORDER_SELLER_SUCCESS = 'PATCH_ORDER_SELLER_SUCCESS';
export const PATCH_ORDER_SELLER_FAIL = 'PATCH_ORDER_SELLER_FAIL';
export const PATCH_ORDER_SELLER_LOADING = 'PATCH_ORDER_SELLER_LOADING';

// SELLER BANNER
export const GET_BANNER_SELLER_SUCCESS = 'GET_BANNER_SELLER_SUCCESS';
export const GET_BANNER_SELLER_FAIL = 'GET_BANNER_SELLER_FAIL';
export const GET_BANNER_SELLER_LOADING = 'GET_BANNER_SELLER_LOADING';
