name: Build-production
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  install-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install npm dependencies
          run: |
            yarn install
        - name: Test
          run |
            yarn test -u         

  build-android:
      needs: install-and-test
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - name: Install npm dependencies
          run: |
            yarn install
        - name: Build Android Release
          run: |
            cd android && chmod +x ./gradlew && ./gradlew assembleRelease
        - name: Upload Artifact to appcenter-production
          uses: wzieba/AppCenter-Github-Action@v1
          with:
            appName: 006Axel/SecondHand
            token: ${{secrets.APP_CENTER_TOKEN}}
            group: SecondHand-production
            file: android/app/build/outputs/apk/release/app-release.apk
            notifyTesters: true
            debug: false  